# Generated by Django 4.2 on 2023-06-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorName',
            new_name='List',
        ),
    ]
