# Generated by Django 4.2 on 2023-06-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_doctorname_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
