# Generated by Django 4.2 on 2023-06-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime_field',
            field=models.DateField(),
        ),
    ]
